
export default class CommonConstants {
  static readonly INDEX_MESSAGE: string = 'Index Page：页面跳转和参数接收';
  static readonly FONT_SIZE: string = '38fp';
  static readonly FULL_WIDTH: string = '100%';
  static readonly FULL_HEIGHT: string = '100%';
  static readonly BUTTON_FONT_SIZE: string = '20fp';
  static readonly BUTTON_FONT_SIZE1: string = '12fp';
  static readonly BUTTON_WIDTH: string = '296vp';
  static readonly BUTTON_HEIGHT: string = '40vp';
  static readonly LAYOUT_HEIGHT: string = '80%';

  static readonly SECOND_URL: string = 'pages/SecondPage';
  static readonly SECOND_SRC_MSG: string = 'Index页面传来的数据';
  static readonly SECOND_MESSAGE: string = 'Second Page：页面返回和参数接收';
  static readonly SECOND_SRC_PARAM: string = 'src';

  static readonly INDEX_URL: string = 'pages/IndexPage';
  static readonly INDEX_SRC_MSG: string = 'Second页面传来的数据';
  static readonly INDEX_SRC_PARAM: string = 'src';
}